
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: www-rails_development

test:
  <<: *default
  database: www_rails_test
  username: <%= ENV['TRAVIS'] == 'true' ? 'postgres' : '' %>

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 10 %>
